In [16]:
import pandas as pd
import numpy as np

In [17]:
diam_train = pd.read_csv("../diamonds-datamad0820/train.csv")
diam_test = pd.read_csv("../diamonds-datamad0820/predict.csv")

In [18]:
display(diam_train.head())
display(diam_test.head())

id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.12    Premium     H     SI1   61.6   59.0  6.67  6.63  4.10   5363
1   1   1.14  Very Good     E     SI2   60.0   54.0  6.74  6.97  4.11   5593
2   2   0.90  Very Good     D     SI2   60.3   63.0  6.12  6.22  3.72   3534
3   3   0.71      Ideal     E     VS1   61.9   54.0  5.74  5.76  3.56   3212
4   4   0.34  Very Good     F     SI2   60.0   62.0  4.51  4.55  2.72    447

id  carat        cut color clarity  depth  table     x     y     z
0   0   0.33  Very Good     I      IF   62.0   58.0  4.44  4.46  2.76
1   1   1.21  Very Good     D     SI2   62.4   58.0  6.77  6.83  4.24
2   2   1.06  Very Good     D     SI1   59.3   60.0  6.64  6.71  3.96
3   3   0.36      Ideal     E    VVS1   61.4   57.0  4.64  4.61  2.54
4   4   0.70      Ideal     E     VS1   62.3   54.0  5.67  5.72  3.55

In [19]:
print(diam_train.shape)
print(diam_test.shape)

(40455, 11)
(13485, 10)


In [20]:
print(diam_train.info())
print(diam_test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40455 entries, 0 to 40454
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   id       40455 non-null  int64  
 1   carat    40455 non-null  float64
 2   cut      40455 non-null  object 
 3   color    40455 non-null  object 
 4   clarity  40455 non-null  object 
 5   depth    40455 non-null  float64
 6   table    40455 non-null  float64
 7   x        40455 non-null  float64
 8   y        40455 non-null  float64
 9   z        40455 non-null  float64
 10  price    40455 non-null  int64  
dtypes: float64(6), int64(2), object(3)
memory usage: 3.4+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13485 entries, 0 to 13484
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   id       13485 non-null  int64  
 1   carat    13485 non-null  float64
 2   cut      13485 non-null  object 
 3   color    13485 non-null  o

In [21]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
for column in diam_train[["cut", "color", "clarity"]]:
    diam_train[column] = le.fit_transform(diam_train[column])

In [22]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
for column in diam_test[["cut", "color", "clarity"]]:
    diam_test[column] = le.fit_transform(diam_test[column])

In [23]:
print(diam_train.info())
print(diam_test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40455 entries, 0 to 40454
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   id       40455 non-null  int64  
 1   carat    40455 non-null  float64
 2   cut      40455 non-null  int64  
 3   color    40455 non-null  int64  
 4   clarity  40455 non-null  int64  
 5   depth    40455 non-null  float64
 6   table    40455 non-null  float64
 7   x        40455 non-null  float64
 8   y        40455 non-null  float64
 9   z        40455 non-null  float64
 10  price    40455 non-null  int64  
dtypes: float64(6), int64(5)
memory usage: 3.4 MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13485 entries, 0 to 13484
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   id       13485 non-null  int64  
 1   carat    13485 non-null  float64
 2   cut      13485 non-null  int64  
 3   color    13485 non-null  int64  
 4   

In [24]:
X_train = diam_train[["carat", "cut", "color", "clarity", "depth", "table", "x", "y", "z"]]
X_test = diam_test[["carat", "cut", "color", "clarity", "depth", "table", "x", "y", "z"]]
y_train = diam_train["price"]

In [25]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)

(40455, 9)
(13485, 9)
(40455,)


## ExtraTreesRegressor

In [35]:
from sklearn.ensemble import ExtraTreesRegressor
reg = ExtraTreesRegressor(n_estimators=500, max_depth=20, min_samples_split=8, max_features= "auto", random_state=4).fit(X_train, y_train)
y_pred = reg.predict(X_test)
y_pred

array([ 746.48822855, 6035.69671042, 5868.39805423, ..., 2511.85328704,
       1290.0297093 , 1084.80707041])

In [37]:
parameters = { 
    "n_estimators": [300, 400, 500],
    "max_depth": [20, 40, 60],
    "min_samples_split": [6, 8, 10],
    "random_state": [2, 4, 6]
}

In [38]:
from sklearn.model_selection import GridSearchCV

etr = ExtraTreesRegressor()
grid = GridSearchCV(estimator=etr,param_grid=parameters,verbose=1,n_jobs=-1,cv=5)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 81 candidates, totalling 405 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  7.8min
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed: 34.8min
[Parallel(n_jobs=-1)]: Done 405 out of 405 | elapsed: 77.3min finished


GridSearchCV(cv=5, estimator=ExtraTreesRegressor(), n_jobs=-1,
             param_grid={'max_depth': [20, 40, 60],
                         'min_samples_split': [6, 8, 10],
                         'n_estimators': [300, 400, 500],
                         'random_state': [2, 4, 6]},
             verbose=1)

In [39]:
grid.best_params_

{'max_depth': 20,
 'min_samples_split': 8,
 'n_estimators': 500,
 'random_state': 4}

## RandomForestRegressor

In [43]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=400, max_depth=20, min_samples_split=6, max_features= "auto", random_state=4)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([ 792.31619534, 5965.49784113, 5827.73665475, ..., 2539.28762878,
       1269.45549456, 1080.04103197])

In [44]:
parameters = { 
    "n_estimators": [300, 400, 500],
    "max_depth": [20, 40, 60],
    "min_samples_split": [6, 8, 10],
    "random_state": [2, 4, 6]
}

In [45]:
from sklearn.model_selection import GridSearchCV

rfr = RandomForestRegressor()
grid = GridSearchCV(estimator=rfr,param_grid=parameters,verbose=1,n_jobs=-1,cv=5)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 81 candidates, totalling 405 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed: 14.3min
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed: 58.3min
[Parallel(n_jobs=-1)]: Done 405 out of 405 | elapsed: 122.1min finished


GridSearchCV(cv=5, estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'max_depth': [20, 40, 60],
                         'min_samples_split': [6, 8, 10],
                         'n_estimators': [300, 400, 500],
                         'random_state': [2, 4, 6]},
             verbose=1)

In [46]:
grid.best_params_

{'max_depth': 20,
 'min_samples_split': 6,
 'n_estimators': 400,
 'random_state': 4}

## VotingRegressor

In [51]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import VotingRegressor

r1 = ExtraTreesRegressor(n_estimators=500, max_depth=20, min_samples_split=8, max_features= "auto", random_state=4) 
r2 = RandomForestRegressor(n_estimators=400, max_depth=20, min_samples_split=6, max_features= "auto", random_state=4)

model = VotingRegressor([('etr', r1), ('rf', r2)])

model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([ 772.59548875, 6004.26676658, 5837.27522989, ..., 2522.51067089,
       1280.31438028, 1076.85824554])

In [52]:
diam_test["price"] = y_pred
diam_submission = diam_test[["id", "price"]]
diam_submission

filename = "Diamonds submission.csv"

diam_submission.to_csv(f"../outputs/{filename}",index=False)
print("Saved file: " + filename)

Saved file: Diamonds submission.csv
