In [1]:
import pandas as pd
import numpy as np

In [50]:
diam_train = pd.read_csv("../diamonds-datamad0820/train.csv")
diam_test = pd.read_csv("../diamonds-datamad0820/predict.csv")

In [51]:
display(diam_train.head())
display(diam_test.head())

id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.12    Premium     H     SI1   61.6   59.0  6.67  6.63  4.10   5363
1   1   1.14  Very Good     E     SI2   60.0   54.0  6.74  6.97  4.11   5593
2   2   0.90  Very Good     D     SI2   60.3   63.0  6.12  6.22  3.72   3534
3   3   0.71      Ideal     E     VS1   61.9   54.0  5.74  5.76  3.56   3212
4   4   0.34  Very Good     F     SI2   60.0   62.0  4.51  4.55  2.72    447

id  carat        cut color clarity  depth  table     x     y     z
0   0   0.33  Very Good     I      IF   62.0   58.0  4.44  4.46  2.76
1   1   1.21  Very Good     D     SI2   62.4   58.0  6.77  6.83  4.24
2   2   1.06  Very Good     D     SI1   59.3   60.0  6.64  6.71  3.96
3   3   0.36      Ideal     E    VVS1   61.4   57.0  4.64  4.61  2.54
4   4   0.70      Ideal     E     VS1   62.3   54.0  5.67  5.72  3.55

In [52]:
print(diam_train.shape)
print(diam_test.shape)

(40455, 11)
(13485, 10)


In [53]:
print(diam_train.info())
print(diam_test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40455 entries, 0 to 40454
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   id       40455 non-null  int64  
 1   carat    40455 non-null  float64
 2   cut      40455 non-null  object 
 3   color    40455 non-null  object 
 4   clarity  40455 non-null  object 
 5   depth    40455 non-null  float64
 6   table    40455 non-null  float64
 7   x        40455 non-null  float64
 8   y        40455 non-null  float64
 9   z        40455 non-null  float64
 10  price    40455 non-null  int64  
dtypes: float64(6), int64(2), object(3)
memory usage: 3.4+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13485 entries, 0 to 13484
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   id       13485 non-null  int64  
 1   carat    13485 non-null  float64
 2   cut      13485 non-null  object 
 3   color    13485 non-null  o

In [54]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
for column in diam_train[["cut", "color", "clarity"]]:
    diam_train[column] = le.fit_transform(diam_train[column])

In [55]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
for column in diam_test[["cut", "color", "clarity"]]:
    diam_test[column] = le.fit_transform(diam_test[column])

In [56]:
print(diam_train.info())
print(diam_test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40455 entries, 0 to 40454
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   id       40455 non-null  int64  
 1   carat    40455 non-null  float64
 2   cut      40455 non-null  int64  
 3   color    40455 non-null  int64  
 4   clarity  40455 non-null  int64  
 5   depth    40455 non-null  float64
 6   table    40455 non-null  float64
 7   x        40455 non-null  float64
 8   y        40455 non-null  float64
 9   z        40455 non-null  float64
 10  price    40455 non-null  int64  
dtypes: float64(6), int64(5)
memory usage: 3.4 MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13485 entries, 0 to 13484
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   id       13485 non-null  int64  
 1   carat    13485 non-null  float64
 2   cut      13485 non-null  int64  
 3   color    13485 non-null  int64  
 4   

In [72]:
X_train = diam_train[["carat", "cut", "color", "clarity", "depth", "table", "x", "y", "z"]]
X_test = diam_test[["carat", "cut", "color", "clarity", "depth", "table", "x", "y", "z"]]
y_train = diam_train["price"]

In [73]:
from sklearn.model_selection import train_test_split

y_test = train_test_split(y_train, test_size = 1/3)

In [74]:
y_test[1]

2544     1046
9638     2246
13618     692
30731    7917
28124     501
         ... 
34238     650
18060    3503
6245      772
27851     825
26673    4284
Name: price, Length: 13485, dtype: int64

## LinearRegression

In [12]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([-1191.14734863,  7691.51645501,  6200.30645983, ...,
        3241.11561014,  1257.24269787,  1453.51645938])

In [13]:
from sklearn.metrics import mean_squared_error

print("RMSE", round(np.sqrt(mean_squared_error(y_test[1],y_pred)),3))

RMSE 5481.55


## DecisionTreeRegressor

In [60]:
from sklearn.tree import DecisionTreeRegressor

regressor = DecisionTreeRegressor()
#cross_val_score(regressor, X, y, cv=10)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
y_pred

array([ 891., 5889., 5659., ..., 2718., 1378., 1132.])

In [61]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test[1],y_pred)),3))

RMSE 5643.617


In [16]:
diam_test["price"] = y_pred
diam_submission = diam_test[["id", "price"]]
diam_submission

id    price
0          0    891.0
1          1   5894.0
2          2   5659.0
3          3   1119.0
4          4   3345.0
...      ...      ...
13480  13480  15291.0
13481  13481    891.0
13482  13482   2362.0
13483  13483   1214.0
13484  13484   1132.0

[13485 rows x 2 columns]

In [17]:
filename = "Diamonds submission.csv"

diam_submission.to_csv(f"../outputs/{filename}",index=False)
print("Saved file: " + filename)

Saved file: Diamonds submission.csv


## ExtraTreesRegressor

In [75]:
from sklearn.ensemble import ExtraTreesRegressor
reg = ExtraTreesRegressor(n_estimators=400, max_depth=20, min_samples_split=20, random_state=10).fit(X_train, y_train)
y_pred = reg.predict(X_test)
y_pred

array([ 738.17995141, 5993.05969037, 5864.44935021, ..., 2530.84895825,
       1295.89842997, 1092.50949864])

In [77]:
diam_test["price"] = y_pred
diam_submission = diam_test[["id", "price"]]
diam_submission

filename = "Diamonds submission.csv"

diam_submission.to_csv(f"../outputs/{filename}",index=False)
print("Saved file: " + filename)

Saved file: Diamonds submission.csv


In [76]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test[1],y_pred)),3))

RMSE 5569.586


## HistGradientBoostingRegressor

In [21]:
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingRegressor

est = HistGradientBoostingRegressor().fit(X_train, y_train)
y_pred = est.predict(X_test)
y_pred

array([ 736.42433134, 6127.32555428, 5972.88782765, ..., 2412.11984491,
       1357.18602112, 1211.86343958])

In [22]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test[1],y_pred)),3))

RMSE 5611.943


## GradientBoostingRegressor

In [23]:
from sklearn.ensemble import GradientBoostingRegressor

reg = GradientBoostingRegressor(random_state=0)
reg.fit(X_train, y_train)
y_pred = reg.predict(X_test)
y_pred

array([ 858.37749599, 6588.61549327, 6265.54624889, ..., 2254.07230904,
       1325.80875816, 1206.92976283])

In [24]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test[1],y_pred)),3))

RMSE 5570.516


## ARDRegression

In [25]:
from sklearn.linear_model import ARDRegression

model = ARDRegression()

model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([-1191.78752593,  7689.72006026,  6198.23640539, ...,
        3240.54823268,  1258.04870663,  1451.19766291])

In [26]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test[1],y_pred)),3))

RMSE 5481.543


## RandomForestRegressor

In [27]:
from sklearn.ensemble import RandomForestRegressor

regr = RandomForestRegressor(max_depth=2, random_state=0)
regr.fit(X_train, y_train)
y_pred = regr.predict(X_test)
y_pred

array([1049.97878163, 6167.47563466, 6167.47563466, ..., 1049.97878163,
       1049.97878163, 1049.97878163])

In [28]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test[1],y_pred)),3))

RMSE 5419.368


## MLPRegressor

In [29]:
from sklearn.neural_network import MLPRegressor

regr = MLPRegressor(random_state=1, max_iter=500).fit(X_train, y_train)
y_pred = regr.predict(X_test)
y_pred

/usr/local/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


array([ 372.63753898, 8251.8595238 , 5874.85271882, ..., 2799.62088752,
       1468.6371235 , 1850.37578985])

In [30]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test[1],y_pred)),3))

RMSE 5547.363


## LassoCV

In [31]:
from sklearn.linear_model import LassoCV

model = LassoCV()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([-1217.22875459,  7692.35160778,  6219.86490953, ...,
        3249.71250361,  1272.96765461,  1468.84237349])

In [32]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test[1],y_pred)),3))

RMSE 5472.746


## Ridge

In [33]:
from sklearn.linear_model import Ridge
clf = Ridge(alpha=1.0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_pred

array([-1192.25723683,  7691.76484532,  6201.61599314, ...,
        3241.77592   ,  1258.19833136,  1454.59374849])

In [34]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test[1],y_pred)),3))

RMSE 5481.035


## RidgeCV

In [35]:
from sklearn.linear_model import RidgeCV

model = RidgeCV()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([-1192.25723711,  7691.76484521,  6201.61599295, ...,
        3241.77591992,  1258.19833106,  1454.59374831])

In [36]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test[1],y_pred)),3))

RMSE 5481.035


## ElasticNetCV

In [37]:
from sklearn.linear_model import ElasticNetCV

model = ElasticNetCV()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([2333.79348158, 5311.05561346, 5129.3659467 , ..., 2945.17536187,
       3109.92970749, 3056.37060104])

In [38]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test[1],y_pred)),3))

RMSE 4338.088


## AdaBoostRegressor

In [39]:
from sklearn.ensemble import AdaBoostRegressor

regr = AdaBoostRegressor(random_state=0, n_estimators=100)
regr.fit(X_train, y_train)
y_pred = regr.predict(X_test)
y_pred

array([2071.88318357, 9316.64440388, 8757.8340465 , ..., 2790.64369748,
       2859.7160804 , 2923.8136646 ])

In [40]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test[1],y_pred)),3))

RMSE 5543.431


## StackingRegressor

In [41]:
from sklearn.svm import LinearSVR
from sklearn.ensemble import StackingRegressor
estimators = [
    ('lr', RidgeCV()),
    ('svr', LinearSVR(random_state=42))
]
reg = StackingRegressor(
    estimators=estimators,
    final_estimator=RandomForestRegressor(n_estimators=10,
                                          random_state=42)
)
reg.fit(X_train, y_train)
y_pred = reg.predict(X_test)
y_pred

array([ 504.5, 7104.1, 6682.6, ..., 2721.5, 1336.5, 1514.3])

In [42]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test[1],y_pred)),3))

RMSE 5570.236


## VotingRegressor

In [43]:
from sklearn.ensemble import VotingRegressor
r1 = LinearRegression()
r2 = RandomForestRegressor(n_estimators=10, random_state=1)
er = VotingRegressor([('lr', r1), ('rf', r2)])
er.fit(X_train, y_train)
y_pred = er.predict(X_test)
y_pred

array([-182.02367431, 6722.2582275 , 6002.40322991, ..., 2990.80780507,
       1270.12134893, 1275.60822969])

In [44]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test[1],y_pred)),3))

RMSE 5515.141


## SGDRegressor

In [45]:
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

reg = make_pipeline(StandardScaler(),
                    SGDRegressor(max_iter=1000, tol=1e-3))
reg.fit(X_train, y_train)
y_pred = reg.predict(X_test)
y_pred

array([-1231.13544263,  7694.87054225,  6164.89497873, ...,
        3319.86812005,  1228.63708326,  1467.96764939])

In [46]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test[1],y_pred)),3))

RMSE 5476.563
