In [1]:
import pandas as pd
import numpy as np

In [2]:
diamonds = pd.read_csv("../diamonds-datamad0820/train.csv")

In [3]:
diamonds.head()

id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.12    Premium     H     SI1   61.6   59.0  6.67  6.63  4.10   5363
1   1   1.14  Very Good     E     SI2   60.0   54.0  6.74  6.97  4.11   5593
2   2   0.90  Very Good     D     SI2   60.3   63.0  6.12  6.22  3.72   3534
3   3   0.71      Ideal     E     VS1   61.9   54.0  5.74  5.76  3.56   3212
4   4   0.34  Very Good     F     SI2   60.0   62.0  4.51  4.55  2.72    447

In [4]:
diamonds.set_index("id", inplace=True)

In [5]:
diamonds.head()

carat        cut color clarity  depth  table     x     y     z  price
id                                                                       
0    1.12    Premium     H     SI1   61.6   59.0  6.67  6.63  4.10   5363
1    1.14  Very Good     E     SI2   60.0   54.0  6.74  6.97  4.11   5593
2    0.90  Very Good     D     SI2   60.3   63.0  6.12  6.22  3.72   3534
3    0.71      Ideal     E     VS1   61.9   54.0  5.74  5.76  3.56   3212
4    0.34  Very Good     F     SI2   60.0   62.0  4.51  4.55  2.72    447

In [6]:
diamonds.shape

(40455, 10)

In [7]:
diamonds.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 40455 entries, 0 to 40454
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   carat    40455 non-null  float64
 1   cut      40455 non-null  object 
 2   color    40455 non-null  object 
 3   clarity  40455 non-null  object 
 4   depth    40455 non-null  float64
 5   table    40455 non-null  float64
 6   x        40455 non-null  float64
 7   y        40455 non-null  float64
 8   z        40455 non-null  float64
 9   price    40455 non-null  int64  
dtypes: float64(6), int64(1), object(3)
memory usage: 3.4+ MB


In [8]:
diamonds.cut.value_counts()

Ideal        16250
Premium      10342
Very Good     9026
Good          3639
Fair          1198
Name: cut, dtype: int64

In [9]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
diamonds.cut = le.fit_transform(diamonds.cut)

In [10]:
diamonds.color.value_counts()

G    8565
E    7344
F    7162
H    6147
D    5063
I    4052
J    2122
Name: color, dtype: int64

In [11]:
le = preprocessing.LabelEncoder()
diamonds.color = le.fit_transform(diamonds.color)

In [12]:
diamonds.clarity.value_counts()

SI1     9806
VS2     9204
SI2     6865
VS1     6099
VVS2    3778
VVS1    2776
IF      1365
I1       562
Name: clarity, dtype: int64

In [13]:
le = preprocessing.LabelEncoder()
diamonds.clarity = le.fit_transform(diamonds.clarity)

In [14]:
diamonds.head()

carat  cut  color  clarity  depth  table     x     y     z  price
id                                                                   
0    1.12    3      4        2   61.6   59.0  6.67  6.63  4.10   5363
1    1.14    4      1        3   60.0   54.0  6.74  6.97  4.11   5593
2    0.90    4      0        3   60.3   63.0  6.12  6.22  3.72   3534
3    0.71    2      1        4   61.9   54.0  5.74  5.76  3.56   3212
4    0.34    4      2        3   60.0   62.0  4.51  4.55  2.72    447

In [248]:
columnas = [a for a in diamonds.columns if a not in ["price"]]
X = diamonds[columnas]
y = diamonds["price"]

In [249]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3)

## LinearRegression

In [17]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [18]:
y_pred

array([4975.6914035 , 7301.08164155, 1477.47261844, ..., 8526.98509678,
       5225.72860864, 3081.56740579])

In [19]:
# explained_variance_score, max_error, mean_absolute_error, mean_squared_error, mean_squared_log_error.
# median_absolute_error, r2_score, mean_poisson_deviance, mean_gamma_deviance, mean_tweedie_deviance.

In [20]:
from sklearn.metrics import  explained_variance_score, max_error, mean_absolute_error, mean_squared_error, r2_score

print("RMSE", round(np.sqrt(mean_squared_error(y_test,y_pred)),3))

Explained_variance_score 0.871
Max_error 46498.945
MAE 872.438
RMSE 1433.796
R2_score 0.871


## ARDRegression

In [21]:
from sklearn.linear_model import ARDRegression

model = ARDRegression()

model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([4979.04794954, 7301.13422242, 1477.58079872, ..., 8527.51938272,
       5225.27032587, 3082.22724574])

In [22]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test,y_pred)),3))

Explained_variance_score 0.871
Max_error 45445.014
MAE 872.193
RMSE 1430.685
R2_score 0.871


## DecisionTreeRegressor

In [23]:
from sklearn.tree import DecisionTreeRegressor

regressor = DecisionTreeRegressor()
#cross_val_score(regressor, X, y, cv=10)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
y_pred

array([4729., 7568., 1388., ..., 7233., 4783., 3126.])

In [25]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test,y_pred)),3))

Explained_variance_score 0.962
Max_error 10515.0
MAE 381.826
RMSE 774.982
R2_score 0.962


## RandomForestRegressor

In [26]:
from sklearn.ensemble import RandomForestRegressor

regr = RandomForestRegressor(max_depth=2, random_state=0)
regr.fit(X_train, y_train)
y_pred = regr.predict(X_test)
y_pred

array([6178.98582191, 6178.98582191, 1051.97934367, ..., 7859.08743204,
       6178.98582191, 1051.97934367])

In [27]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test,y_pred)),3))

Explained_variance_score 0.831
Max_error 12363.014
MAE 1028.465
RMSE 1637.052
R2_score 0.831


## MLPRegressor

In [28]:
from sklearn.neural_network import MLPRegressor

regr = MLPRegressor(random_state=1, max_iter=500).fit(X_train, y_train)
y_pred = regr.predict(X_test)
y_pred

/usr/local/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


array([5083.31356857, 7678.73658351, 1746.57647462, ..., 7264.24901271,
       4850.23609241, 2353.73498969])

In [29]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test,y_pred)),3))

Explained_variance_score 0.889
Max_error 78971.278
MAE 626.737
RMSE 1330.934
R2_score 0.889


## LassoCV

In [30]:
from sklearn.linear_model import LassoCV

model = LassoCV()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([5109.11215651, 7374.81252442, 1454.35675253, ..., 8526.55281645,
       5220.20302546, 3088.01164785])

In [31]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test,y_pred)),3))

Explained_variance_score 0.883
Max_error 22247.54
MAE 873.777
RMSE 1365.52
R2_score 0.883


## Ridge

In [32]:
from sklearn.linear_model import Ridge
clf = Ridge(alpha=1.0)
clf.fit(X, y)
y_pred = clf.predict(X_test)
y_pred

array([5001.47926207, 7363.98195755, 1445.94930675, ..., 8550.14360374,
       5177.89292871, 3073.42397545])

In [33]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test,y_pred)),3))

Explained_variance_score 0.883
Max_error 23074.13
MAE 866.676
RMSE 1365.088
R2_score 0.883


## RidgeCV

In [34]:
from sklearn.linear_model import RidgeCV

model = RidgeCV()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([5028.53870238, 7327.18530664, 1483.50865406, ..., 8507.82073275,
       5245.26464281, 3096.3056526 ])

In [35]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test,y_pred)),3))

Explained_variance_score 0.874
Max_error 40766.622
MAE 877.187
RMSE 1417.594
R2_score 0.874


## ElasticNetCV

In [36]:
from sklearn.linear_model import ElasticNetCV

model = ElasticNetCV()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([5425.10554539, 5489.59729702, 2786.47186347, ..., 6427.99677901,
       4877.01408242, 3389.55034881])

In [37]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test,y_pred)),3))

Explained_variance_score 0.546
Max_error 23746.149
MAE 1893.187
RMSE 2687.004
R2_score 0.546


## AdaBoostRegressor

In [38]:
from sklearn.ensemble import AdaBoostRegressor

regr = AdaBoostRegressor(random_state=0, n_estimators=100)
regr.fit(X_train, y_train)
y_pred = regr.predict(X_test)
y_pred

array([ 5874.80008865, 10569.77034908,  3122.38650307, ...,
       10077.26280661,  6158.51577287,  3575.26647145])

In [39]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test,y_pred)),3))

Explained_variance_score 0.925
Max_error 6437.488
MAE 1244.943
RMSE 1492.769
R2_score 0.86


## ExtraTreesRegressor

In [279]:
from sklearn.ensemble import ExtraTreesRegressor
reg = ExtraTreesRegressor(n_estimators=300, max_depth=20, min_samples_split=10, max_features= "auto", random_state=10).fit(X_train, y_train)
y_pred = reg.predict(X_test)
y_pred

array([14441.09225848,   609.30027197,  4732.36712447, ...,
        3104.64184275, 14073.15603012,  6504.78782762])

In [267]:
parameters = { 
    "n_estimators": [100, 200, 300],
    "max_depth": [10, 20, 30],
    "min_samples_split": [10, 20, 30],
    "max_features": ['auto', 'sqrt', 'log2'],
    "random_state": [6, 8, 10]
}

In [268]:
from sklearn.model_selection import GridSearchCV

etr = ExtraTreesRegressor()
grid = GridSearchCV(estimator=etr,param_grid=parameters,verbose=1,n_jobs=-1,cv=5)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 243 candidates, totalling 1215 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  5.5min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed: 10.3min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed: 18.8min
[Parallel(n_jobs=-1)]: Done 1215 out of 1215 | elapsed: 30.2min finished


GridSearchCV(cv=5, estimator=ExtraTreesRegressor(), n_jobs=-1,
             param_grid={'max_depth': [10, 20, 30],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'min_samples_split': [10, 20, 30],
                         'n_estimators': [100, 200, 300],
                         'random_state': [6, 8, 10]},
             verbose=1)

In [269]:
grid.best_params_

{'max_depth': 20,
 'max_features': 'auto',
 'min_samples_split': 10,
 'n_estimators': 300,
 'random_state': 10}

In [280]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test,y_pred)),3))

RMSE 554.305


In [ ]:
n_estimators=300, max_depth=20, min_samples_split=10, max_features= "auto", random_state=10

## GradientBoostingRegressor

In [42]:
from sklearn.ensemble import GradientBoostingRegressor

reg = GradientBoostingRegressor(random_state=0)
reg.fit(X_train, y_train)
y_pred = reg.predict(X_test)
y_pred

array([4469.21487043, 7943.06436311, 1523.16490482, ..., 8295.11552789,
       4647.17007334, 2508.50327007])

In [43]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test,y_pred)),3))

Explained_variance_score 0.97
Max_error 11910.84
MAE 373.062
RMSE 690.273
R2_score 0.97


## StackingRegressor

In [44]:
from sklearn.svm import LinearSVR
from sklearn.ensemble import StackingRegressor
estimators = [
    ('lr', RidgeCV()),
    ('svr', LinearSVR(random_state=42))
]
reg = StackingRegressor(
    estimators=estimators,
    final_estimator=RandomForestRegressor(n_estimators=10,
                                          random_state=42)
)
reg.fit(X_train, y_train)
y_pred = reg.predict(X_test)
y_pred

array([4102.6, 8329.4, 1541.2, ..., 8939.7, 6365.3, 1906. ])

In [45]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test,y_pred)),3))

Explained_variance_score 0.896
Max_error 13164.4
MAE 704.064
RMSE 1284.639
R2_score 0.896


## VotingRegressor

In [46]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import VotingRegressor
r1 = LinearRegression()
r2 = RandomForestRegressor(n_estimators=10, random_state=1)
er = VotingRegressor([('lr', r1), ('rf', r2)])
er.fit(X, y)
y_pred = er.predict(X_test)
y_pred

array([4699.39976296, 7387.069353  , 1409.71603632, ..., 8004.86000055,
       4562.98158387, 3199.33646707])

In [47]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test,y_pred)),3))

Explained_variance_score 0.966
Max_error 11400.185
MAE 458.435
RMSE 730.671
R2_score 0.966


## HistGradientBoostingRegressor

In [48]:
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingRegressor

est = HistGradientBoostingRegressor().fit(X_train, y_train)
y_pred = est.predict(X_test)
y_pred

array([4714.52973501, 7611.77135426, 1427.83321079, ..., 7974.24721832,
       4448.0613252 , 3306.91235493])

In [49]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test,y_pred)),3))

Explained_variance_score 0.98
Max_error 7154.07
MAE 296.759
RMSE 570.605
R2_score 0.98


## SGDRegressor

In [50]:
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

reg = make_pipeline(StandardScaler(),
                    SGDRegressor(max_iter=1000, tol=1e-3))
reg.fit(X_train, y_train)
y_pred = reg.predict(X_test)
y_pred

array([5091.04684992, 7356.82090249, 1479.90184556, ..., 8542.84147885,
       5206.60049638, 3160.897572  ])

In [51]:
print("RMSE", round(np.sqrt(mean_squared_error(y_test,y_pred)),3))

Explained_variance_score 0.883
Max_error 23162.113
MAE 876.823
RMSE 1366.54
R2_score 0.883
